import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Providers from "@/providers/Providers";
import Modal from "@/components/modal/CreatePlaylist";
import ProfilePopup from "@/components/navbar/ProfilePopup";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={poppins.className + " overflow-hidden"}>
        <Providers>
          <Navbar>
            {children}
            <Modal />
          </Navbar>
        </Providers>
      </body>
    </html>
  );
}
