import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../../globals.css";
import BibliothequeNavBar from "@/components/navbar/BibliothequeNavBar";
import { usePathname } from 'next/navigation'

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div className="flex min-h-screen flex-col gap-8 h-screen overflow-auto">
    <h1 className="text-4xl font-semibold">Bibliothèque</h1>
    <BibliothequeNavBar />
    {children}
    </div>
  );
}
